# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      addresses: [192.168.1.4/24]
      gateway4: 192.168.1.1
      nameservers:
        search: [dominio.amazon]
        addresses: [192.168.1.4]
  version: 2
